### ISSUE TITLE
"Run Test" CI in multiple OS

### ISSUE THREAD

**Issue by ChaiyoKung** [ChaiyoKung/dup-detector#18]
# Requirement
Modified `.github/workflows/run-demo.yml` to run with multiple OS
I need to run with "Linux", "Windows" and "MacOS"
You can use `matrix` like this ([Learn more](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#using-a-matrix-strategy))
```yml
jobs:
  test-cli:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
```
You can see available OS at [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
